### ISSUE TITLE
SQLSyntaxErrorException on Atlassian Bitbucket v7.0.1

### ISSUE THREAD

**Issue by kszorin** [reconquest/atlassian-pull-request-labels#3]
We have Atlassian Bitbucket v7.0.1. Set up plugin without problems.
But we haven't any GUI controls in pull requests. And we have problems in plugin logs:

```
2020-04-21 23:02:55,807 ERROR [http-nio-9102-exec-139] turnaev @1UMQQ5Gx1382x60567886x3 1hrtqee 10.5.10.146,172.16.115.127 "GET /rest/io.reconquest.bitbucket.labels/1.0/MTALL/comic/pull-requests/ HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: There was a SQL exception thrown by the Active Objects library:
Database:
    - name:Oracle
    - version:Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
    - minor version:2
    - major version:12
Driver:
    - name:Oracle JDBC driver
    - version:12.2.0.1.0

 

java.sql.SQLSyntaxErrorException: ORA-00904: "item"."ID": invalid identifier

 

com.atlassian.activeobjects.internal.ActiveObjectsSqlException: There was a SQL exception thrown by the Active Objects library:
Database:
    - name:Oracle
    - version:Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
    - minor version:2
    - major version:12
Driver:
    - name:Oracle JDBC driver
    - version:12.2.0.1.0

 

java.sql.SQLSyntaxErrorException: ORA-00904: "item"."ID": invalid identifier

 

    at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.find(EntityManagedActiveObjects.java:152)
    at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects.find(TenantAwareActiveObjects.java:302)
    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
    at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
    at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
    at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
    at io.reconquest.bitbucket.labels.dao.LabelDao.find(LabelDao.java:29)
    at io.reconquest.bitbucket.labels.dao.LabelDao.find(LabelDao.java:59)
    at io.reconquest.bitbucket.labels.rest.PullRequestLabels.listByRepositoryHash(PullRequestLabels.java:142)
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
    at com.atlassian.bitbucket.internal.xcode.web.XcodeUserAgentFilter.doFilter(XcodeUserAgentFilter.java:36)
    at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:75)
    at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:33)
    at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
    at com.atlassian.bitbucket.internal.ratelimit.servlet.filter.RateLimitFilter.doFilter(RateLimitFilter.java:75)
    at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
    at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
    at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:85)
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:112)
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75)
    at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
    at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
    at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
    at com.atlassian.plugin.connect.plugin.auth.oauth2.DefaultSalAuthenticationFilter.doFilter(DefaultSalAuthenticationFilter.java:69)
    at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109)
    at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:37)
    at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:33)
    at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:33)
    at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
    at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:87)
    at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.lang.Thread.run(Thread.java:748)
    ... 264 frames trimmed
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "item"."ID": invalid identifier

 

    at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
    at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
    at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
    at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
    at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
    at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
    at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
    at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4646)
    at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10203)
    at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3775)
    at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
    at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3822)
    at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1165)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
    at net.java.ao.ForwardingPreparedStatement.executeQuery(ForwardingPreparedStatement.java:40)
    at net.java.ao.ParameterMetadataCachingPreparedStatement.executeQuery(ParameterMetadataCachingPreparedStatement.java:10)
    at net.java.ao.EntityManager.find(EntityManager.java:750)
    at net.java.ao.EntityManager.find(EntityManager.java:700)
    at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.find(EntityManagedActiveObjects.java:150)
    ... 40 common frames omitted
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00904: "item"."ID": invalid identifier

 

    at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
    ... 63 common frames omitted

```

**Comment by kovetskiy** [comment]
Hi

@kszorin why did you decide to rate the add-on in Atlassian Marketplace with 1 star and crush the rating before even getting any response for the issue here on GitHub?

**Comment by kszorin** [comment]
Hi! I was too hasty. I've deleted it. Has your rating been restored?
Could you help with this problem, Egor?

**Comment by kovetskiy** [comment]
Thanks! Yes, I'm already trying to reproduce the problem on our side with BB 7 and Oracle 12.2.

I'll keep you posted.

**Comment by kovetskiy** [comment]
@kszorin we were able to reproduce the problem on our side, the same error happens on Oracle 11.2

While the compatibility with oracle is fixed now, there is a big problem with upgrade of Pull Request experience for Bitbucket users since 7.0 and basically there is no back-compatibility. We are going to work on this issue in the next few days. I'll let you know when it will be fixed.

**Comment by kszorin** [comment]
@kovetskiy , thank you for fast reaction! Ok! I'll be waiting.

**Comment by kovetskiy** [comment]
@kszorin Please check the latest version of the add-on: v7.0.0

You can download it from the official marketplace page: https://marketplace.atlassian.com/apps/1219710/free-pull-request-labels-by-reconquest/version-history#b1000150

or can click Upgrade in your Bitbucket instance

Please confirm that the fix works for you too.

**Comment by kszorin** [comment]
Excellent!!!! Thanks!!!!

I won't forget to write a review шт Attlassian market place in a few days.
