### ISSUE TITLE
Can't enable plugin after plugin update to 7.1

### ISSUE THREAD

**Issue by viceice** [reconquest/atlassian-pull-request-labels#7]
```
4/27/2020 6:41:59 AM2020-04-27 06:41:59,739 ERROR [ThreadPoolAsyncTaskExecutor::Thread 42]  c.a.plugin.osgi.factory.OsgiPlugin Unable to start the plugin container for plugin 'io.reconquest.bitbucket.labels'
4/27/2020 6:41:59 AMorg.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [bundle://128.0:0/META-INF/spring/atlassian-plugins-components.xml]; nested exception is java.lang.IllegalStateException: The bundle is uninstalled.
4/27/2020 6:41:59 AM	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:420)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:171)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:141)
4/27/2020 6:41:59 AM	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
4/27/2020 6:41:59 AM	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:637)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$800(AbstractDelegatedExecutionApplicationContext.java:57)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$3.run(AbstractDelegatedExecutionApplicationContext.java:239)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.startRefresh(AbstractDelegatedExecutionApplicationContext.java:217)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageOne(DependencyWaiterApplicationContextExecutor.java:224)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.refresh(DependencyWaiterApplicationContextExecutor.java:177)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:154)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.activator.LifecycleManager$1.run(LifecycleManager.java:213)
4/27/2020 6:41:59 AM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
4/27/2020 6:41:59 AM	at java.lang.Thread.run(Thread.java:748)
4/27/2020 6:41:59 AM	... 6 frames trimmed
4/27/2020 6:41:59 AMCaused by: java.lang.IllegalStateException: The bundle is uninstalled.
4/27/2020 6:41:59 AM	at org.apache.felix.framework.Felix.getBundleResources(Felix.java:1706)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.util.BundleDelegatingClassLoader.getResources(BundleDelegatingClassLoader.java:186)
4/27/2020 6:41:59 AM	at org.springframework.core.io.support.PropertiesLoaderUtils.loadAllProperties(PropertiesLoaderUtils.java:178)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$Plugin.resolve(NamespacePlugins.java:77)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$5.operate(NamespacePlugins.java:209)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$5.operate(NamespacePlugins.java:205)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.LazyBundleRegistry.apply(LazyBundleRegistry.java:159)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins.doResolve(NamespacePlugins.java:205)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins.resolve(NamespacePlugins.java:169)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.TrackingUtil$OsgiServiceHandler.invoke(TrackingUtil.java:106)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.DelegatedNamespaceHandlerResolver.resolve(DelegatedNamespaceHandlerResolver.java:55)
4/27/2020 6:41:59 AM	... 15 common frames omitted
4/27/2020 6:41:59 AM2020-04-27 06:41:59,761 ERROR [ThreadPoolAsyncTaskExecutor::Thread 42]  o.e.g.b.e.i.s.ExtenderConfiguration Application context refresh failed (NonValidatingOsgiBundleXmlApplicationContext(bundle=io.reconquest.bitbucket.labels, config=osgibundle:/META-INF/spring/*.xml))
4/27/2020 6:41:59 AMorg.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [bundle://128.0:0/META-INF/spring/atlassian-plugins-components.xml]; nested exception is java.lang.IllegalStateException: The bundle is uninstalled.
4/27/2020 6:41:59 AM	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:420)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:171)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:141)
4/27/2020 6:41:59 AM	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
4/27/2020 6:41:59 AM	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:637)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$800(AbstractDelegatedExecutionApplicationContext.java:57)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$3.run(AbstractDelegatedExecutionApplicationContext.java:239)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.startRefresh(AbstractDelegatedExecutionApplicationContext.java:217)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageOne(DependencyWaiterApplicationContextExecutor.java:224)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.refresh(DependencyWaiterApplicationContextExecutor.java:177)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:154)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.activator.LifecycleManager$1.run(LifecycleManager.java:213)
4/27/2020 6:41:59 AM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
4/27/2020 6:41:59 AM	at java.lang.Thread.run(Thread.java:748)
4/27/2020 6:41:59 AM	... 6 frames trimmed
4/27/2020 6:41:59 AMCaused by: java.lang.IllegalStateException: The bundle is uninstalled.
4/27/2020 6:41:59 AM	at org.apache.felix.framework.Felix.getBundleResources(Felix.java:1706)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.util.BundleDelegatingClassLoader.getResources(BundleDelegatingClassLoader.java:186)
4/27/2020 6:41:59 AM	at org.springframework.core.io.support.PropertiesLoaderUtils.loadAllProperties(PropertiesLoaderUtils.java:178)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$Plugin.resolve(NamespacePlugins.java:77)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$5.operate(NamespacePlugins.java:209)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$5.operate(NamespacePlugins.java:205)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.LazyBundleRegistry.apply(LazyBundleRegistry.java:159)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins.doResolve(NamespacePlugins.java:205)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins.resolve(NamespacePlugins.java:169)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.TrackingUtil$OsgiServiceHandler.invoke(TrackingUtil.java:106)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.DelegatedNamespaceHandlerResolver.resolve(DelegatedNamespaceHandlerResolver.java:55)
4/27/2020 6:41:59 AM	... 15 common frames omitted
4/27/2020 6:41:59 AM2020-04-27 06:41:59,763 ERROR [ThreadPoolAsyncTaskExecutor::Thread 42]  o.e.g.b.e.i.d.s.DependencyWaiterApplicationContextExecutor Unable to create application context for [io.reconquest.bitbucket.labels], unsatisfied dependencies: none
4/27/2020 6:41:59 AMorg.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [bundle://128.0:0/META-INF/spring/atlassian-plugins-components.xml]; nested exception is java.lang.IllegalStateException: The bundle is uninstalled.
4/27/2020 6:41:59 AM	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:420)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:171)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:141)
4/27/2020 6:41:59 AM	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
4/27/2020 6:41:59 AM	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:637)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$800(AbstractDelegatedExecutionApplicationContext.java:57)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$3.run(AbstractDelegatedExecutionApplicationContext.java:239)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.startRefresh(AbstractDelegatedExecutionApplicationContext.java:217)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageOne(DependencyWaiterApplicationContextExecutor.java:224)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.refresh(DependencyWaiterApplicationContextExecutor.java:177)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:154)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.activator.LifecycleManager$1.run(LifecycleManager.java:213)
4/27/2020 6:41:59 AM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
4/27/2020 6:41:59 AM	at java.lang.Thread.run(Thread.java:748)
4/27/2020 6:41:59 AM	... 6 frames trimmed
4/27/2020 6:41:59 AMCaused by: java.lang.IllegalStateException: The bundle is uninstalled.
4/27/2020 6:41:59 AM	at org.apache.felix.framework.Felix.getBundleResources(Felix.java:1706)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.util.BundleDelegatingClassLoader.getResources(BundleDelegatingClassLoader.java:186)
4/27/2020 6:41:59 AM	at org.springframework.core.io.support.PropertiesLoaderUtils.loadAllProperties(PropertiesLoaderUtils.java:178)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$Plugin.resolve(NamespacePlugins.java:77)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$5.operate(NamespacePlugins.java:209)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins$5.operate(NamespacePlugins.java:205)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.LazyBundleRegistry.apply(LazyBundleRegistry.java:159)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins.doResolve(NamespacePlugins.java:205)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.extender.internal.support.NamespacePlugins.resolve(NamespacePlugins.java:169)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.TrackingUtil$OsgiServiceHandler.invoke(TrackingUtil.java:106)
4/27/2020 6:41:59 AM	at org.eclipse.gemini.blueprint.context.support.DelegatedNamespaceHandlerResolver.resolve(DelegatedNamespaceHandlerResolver.java:55)
4/27/2020 6:41:59 AM	... 15 common frames omitted
```

**Comment by kovetskiy** [comment]
Hi, unfortunately, this stacktrace doesn't even mention our code, but while it's said that "bundle is uninstalled", it means that Bitbucket internals were not able to properly upgrade the add-on and now it stuck in half-uninstalled state. Could you please try to reboot your Bitbucket instance?

**Comment by viceice** [comment]
Strange, restarting bitbucket and enable plugin again worked. Thanks
